### ISSUE TITLE
Why did you delete Radetrogen and Taels Prank?

### ISSUE THREAD

**Issue by drumstickguy** [N17Pro3426/ViewerMade#9]
explain please

**Comment by N17Pro3426** [comment]
I added Radetrogen again, cuz BelkasPRO made the destructive version
Taels Prank was removed, cuz BlueDragon hates ZacharyXPeedy, also ZacharyXPeedy asked me to remove it from my GitHub

**Comment by drumstickguy** [comment]
Ok
MINEFREE when tho

чт, 5 дек. 2024 г., 20:02 Doge Kabosu ***@***.***>:

**Comment by N17Pro3426** [comment]
ok, I will send it
